user_num1 = int(input("Enter Integer:\n"))
print("You entered:",user_num1)
print(user_num1,"squared is",user_num1*user_num1)
print("And",user_num1,"cubed is",user_num1*user_num1*user_num1,"!!")
user_num2 = int(input("Enter another Integer:\n"))
print(user_num1,"+",user_num2,"is",user_num1+user_num2)
print(user_num1,"*", user_num2, "is", user_num1*user_num2)